### ISSUE TITLE
Versioned Documentation

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf-mkdoc-theme#71]
## Problem

Some component documentations already includes descriptions and pages for different component versions. This ends up in a very long sub-navigation and duplications of navigations entries.

### Example

zend-expressive with **3** versions: https://docs.zendframework.com/zend-expressive

## Goals for Improvement

* add a version selector
* only show pages of the currently selected version in the sub-navigation
* output a notice if the currently selected version is not the latest
* backward compatibility:
   * no changes in URLs
   * without any changes (in the MkDocs configuration), the result of the rendering must be the same as before

## Suggestion

The current idea is based on an extension of the MkDocs configuration file (`mkdocs.yml`).

New is the extra level in `pages` for the version number and the section `extra`.

### Example (excerpt)

```yaml
docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - v3:
      - "Quick Start": v3/quick-start.md
      - Hydrators:
        - "ArraySerializable": v3/hydrators/array-serializable.md
        - "ObjectProperty": v3/hydrators/object-property.md
        - "Reflection": v3/hydrators/reflection.md
        - "ClassMethods": v3/hydrators/class-methods.md
        - "Delegating": v3/hydrators/delegating.md
        - "Aggregate": v3/hydrators/aggregate.md
      - Strategies:
        - …
      - "Application Integration":
        - "Usage in a zend-mvc-based Application": v3/application-integration/zend-mvc.md
      - Migration:
        - "Migration from version 2": v3/migration.md
    - v2:
      - "Quick Start": v2/quick-start.md
      - Reference:
        - "Filters": v2/filter.md
        - …
    - "_hidden-legacy-page-links":
        - "_quick_start": quick-start.md
        - …
site_name: zend-hydrator
site_description: "Serialize objects to arrays, and vice versa"
repo_url: 'https://github.com/zendframework/zend-hydrator'
markdown_extensions:
  - markdown.extensions.codehilite:
      use_pygments: False
edit_uri: edit/master/${DOCS_DIR}/
extra:
  current_version: v3
  versions:
    - v3
    - v2
```

### Screenshots

![screenshot_2018-12-01 home - zend-hydrator](https://user-images.githubusercontent.com/103362/49326430-77c01300-f552-11e8-8d0e-7e6c0b620697.png)
![screenshot_2018-12-01 quick start - zend-hydrator](https://user-images.githubusercontent.com/103362/49326440-7abb0380-f552-11e8-91aa-d55785028342.png)

## To-do

* [x] Update the Jinja2 templates
* [x] Add CSS for version selector
* [x] Test component with different versions
* [x] Test component without versions

---

Comments and suggestions are welcome!

**Comment by froschdesign** [comment]
ping @weierophinney @settermjd @xtreamwayz

**Comment by xtreamwayz** [comment]
Where is the PR so I can merge it now.

**Comment by weierophinney** [comment]
Totally want this. :+1:

**Comment by froschdesign** [comment]
Fixed with #87
